// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.mastalerek.mytamer.builder;

import com.mastalerek.mytamer.entity.Group;
import com.mastalerek.mytamer.entity.User;

public class GroupBuilder extends GroupBuilderBase<GroupBuilder> {
	public static GroupBuilder group() {
		return new GroupBuilder();
	}

	public GroupBuilder() {
		super(new Group());
	}

	public Group build() {
		return getInstance();
	}
}

class GroupBuilderBase<GeneratorT extends GroupBuilderBase<GeneratorT>> {
	private Group instance;

	protected GroupBuilderBase(Group aInstance) {
		instance = aInstance;
	}

	protected Group getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Integer aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUser(User aValue) {
		instance.setUser(aValue);

		return (GeneratorT) this;
	}

	public UserUserBuilder withUser() {
		User obj = new User();

		withUser(obj);

		return new UserUserBuilder(obj);
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withName(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}

	public class UserUserBuilder extends UserBuilderBase<UserUserBuilder> {
		public UserUserBuilder(User aInstance) {
			super(aInstance);
		}

		@SuppressWarnings("unchecked")
		public GeneratorT endUser() {
			return (GeneratorT) GroupBuilderBase.this;
		}
	}

	public static class UserBuilderBase<GeneratorT extends UserBuilderBase<GeneratorT>> {
		private User instance;

		protected UserBuilderBase(User aInstance) {
			instance = aInstance;
		}

		protected User getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withId(Integer aValue) {
			instance.setId(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withUsername(String aValue) {
			instance.setUsername(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withEmail(String aValue) {
			instance.setEmail(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withPassword(String aValue) {
			instance.setPassword(aValue);

			return (GeneratorT) this;
		}
	}
}
