// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.mastalerek.mytamer.builder;

import com.mastalerek.mytamer.entity.Rank;

public class RankBuilder extends RankBuilderBase<RankBuilder> {
	public static RankBuilder rank() {
		return new RankBuilder();
	}

	public RankBuilder() {
		super(new Rank());
	}

	public Rank build() {
		return getInstance();
	}
}

class RankBuilderBase<GeneratorT extends RankBuilderBase<GeneratorT>> {
	private Rank instance;

	protected RankBuilderBase(Rank aInstance) {
		instance = aInstance;
	}

	protected Rank getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Integer aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withName(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}
}
