// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.mastalerek.mytamer.builder;

import com.mastalerek.mytamer.webmodel.TrainingPlanBasicWebModel;

public class TrainingPlanBasicWebModelBuilder
		extends TrainingPlanBasicWebModelBuilderBase<TrainingPlanBasicWebModelBuilder> {
	public static TrainingPlanBasicWebModelBuilder trainingPlanBasicWebModel() {
		return new TrainingPlanBasicWebModelBuilder();
	}

	public TrainingPlanBasicWebModelBuilder() {
		super(new TrainingPlanBasicWebModel());
	}

	public TrainingPlanBasicWebModel build() {
		return getInstance();
	}
}

class TrainingPlanBasicWebModelBuilderBase<GeneratorT extends TrainingPlanBasicWebModelBuilderBase<GeneratorT>> {
	private TrainingPlanBasicWebModel instance;

	protected TrainingPlanBasicWebModelBuilderBase(TrainingPlanBasicWebModel aInstance) {
		instance = aInstance;
	}

	protected TrainingPlanBasicWebModel getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Integer aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withName(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}
}
