// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.mastalerek.mytamer.builder;

import com.mastalerek.mytamer.webmodel.UserWebModel;

public class UserWebClientModelBuilder extends UserWebClientModelBuilderBase<UserWebClientModelBuilder> {
	public static UserWebClientModelBuilder userWebClientModel() {
		return new UserWebClientModelBuilder();
	}

	public UserWebClientModelBuilder() {
		super(new UserWebModel());
	}

	public UserWebModel build() {
		return getInstance();
	}
}

class UserWebClientModelBuilderBase<GeneratorT extends UserWebClientModelBuilderBase<GeneratorT>> {
	private UserWebModel instance;

	protected UserWebClientModelBuilderBase(UserWebModel aInstance) {
		instance = aInstance;
	}

	protected UserWebModel getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Integer aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUsername(String aValue) {
		instance.setUsername(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEmail(String aValue) {
		instance.setEmail(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPassword(String aValue) {
		instance.setPassword(aValue);

		return (GeneratorT) this;
	}
}
